FROM alpine:3

LABEL author="Achmad Alwani"
LABEL work="IT Flutter" website="https://verbena-bus-67d.notion.site/Kelas-FullStack-Dasar-89cc20ba58b243209683093fd6d151b5"

RUN mkdir hello
RUN echo "Hello Word" > "hello/world.txt"
CMD cat "hello/world.txt"